### ISSUE TITLE
librife.dylib is broken

### ISSUE THREAD

**Issue by hooke007** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#12]
Its size is too small and looks like a shortcut. I think only original builder can load it on his own machine.

**Comment by mafiosnik777** [comment]
> Its size is too small and looks like a shortcut.

No one can figure anything out from that statement alone. Vapoursynth will exactly tell you what it is looking for when it's failing to load a plugin. Provide that first please.

I'd guess it's looking for ncnn & moltenvk and can't find that.

`brew install molten-vk vulkan-headers ncnn`

**Comment by hooke007** [comment]
> librife.dylib is broken

As the title said, the info is output by macos itself.

Here are the vs's log
```
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 3121, in vapoursynth._vpy_evaluate
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 3122, in vapoursynth._vpy_evaluate
[vapoursynth]   File "/Users/hooke007/.config/mpv/test2.vpy", line 4, in <module>
[vapoursynth]     core.std.LoadPlugin(path="/opt/homebrew/lib/librife.dylib")
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2857, in vapoursynth.Function.__call__
[vapoursynth] vapoursynth.Error: Failed to load /opt/homebrew/lib/librife.dylib. Error given: dlopen(/opt/homebrew/lib/librife.dylib, 0x0001): tried: '/opt/homebrew/lib/librife.dylib' (code signature in <87687D6B-C8B7-31FE-A91D-73A873867943> '/opt/homebrew/lib/librife.dylib' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/lib/librife.dylib' (no such file), '/opt/homebrew/lib/librife.dylib' (code signature in <87687D6B-C8B7-31FE-A91D-73A873867943> '/opt/homebrew/lib/librife.dylib' not valid for use in process: library load disallowed by system policy)
```

**Comment by hooke007** [comment]
> Its size is too small and looks like a shortcut.

<img width="889" alt="截屏2023-10-24 18 28 32" src="https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/assets/41094733/a0ed56ed-f792-49ba-98d1-58a2b9d6d8e8">
<img width="889" alt="截屏2023-10-24 18 29 09" src="https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/assets/41094733/e732631a-6e68-410a-a536-04a2f74cced2">

And what magic made it so small...

**Comment by mafiosnik777** [comment]
I'll try to recompile later.
I don't know what changed but it wouldn't let me compile the same way as before and I had to do some workarounds with the Vulkan SDK, which probably lead to this.

**Comment by hooke007** [comment]
I have no idea.
```
[vapoursynth]     cut2 = core.rife.RIFE(clip=cut1, model=9, factor_num=2, factor_den=1, gpu_id=0, gpu_thread=2, sc=True, skip=True, skip_threshold=60.0)
[vapoursynth]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[vapoursynth]   File "src/cython/vapoursynth.pyx", line 2857, in vapoursynth.Function.__call__
[vapoursynth] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 6: invalid start byte
```

**Comment by mafiosnik777** [comment]
> I have no idea.
> 
> ```
> [vapoursynth]     cut2 = core.rife.RIFE(clip=cut1, model=9, factor_num=2, factor_den=1, gpu_id=0, gpu_thread=2, sc=True, skip=True, skip_threshold=60.0)
> [vapoursynth]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [vapoursynth]   File "src/cython/vapoursynth.pyx", line 2857, in vapoursynth.Function.__call__
> [vapoursynth] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 6: invalid start byte
> ```

It's working now, I had the same crash with gpu_thread < 1. No idea what's causing that.

**Comment by hooke007** [comment]
Possible driver issues in vk or ncnn.
There is one issue in original repo(holywu's rife ncnn vk) said gpu_thread could only be set to 1 to make it work. He finally roll back the version of gpu's driver to fix it.

**Comment by mafiosnik777** [comment]
Yeah, that repo is gone now.
