### ISSUE TITLE
librife.dylib is Arm64 only

### ISSUE THREAD

**Issue by grosbecyk** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#13]
Trying to run this on an Intel mac. I get:
`Failed to load /Library/Frameworks/VapourSynth.Framework/lib/vapoursynth/librife.dylib. Error given: dlopen(/Library/Frameworks/VapourSynth.framework/lib/vapoursynth/librife.dylib, 0x0001): tried: '/Library/Frameworks/VapourSynth.framework/lib/vapoursynth/librife.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))`

Looks like it's Apple Silicon only. Is there any Intel binary? Or any tip on how to compile for Intel?

**Comment by mafiosnik777** [comment]
Don't have an Intel Mac anymore. You'd have to compile that yourself. Look at how the github workflow does it.

**Comment by styler00dollar** [comment]
[New release](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/releases/tag/r9_mod_v11).
