### ISSUE TITLE
guide to models

### ISSUE THREAD

**Issue by aeosynth** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#18]
there are currently 44 models, could you add a guide on which to choose, or a link to some guide? should we generally always choose the latest model? should i ask on a different repo?

**Comment by styler00dollar** [comment]
That part is subjective and people have different opinions. Models vary in speed as well. There is no useful guide for this and models get released without much additional information from hzwer. There are a few loss graphs though. As a rough recommendation, use 4.13 for quality and 4.6 for speed. 2.3, 4.9 and 4.12 might also be interesting.
