### ISSUE TITLE
Rife 4.14 lite Ensamble_false not working (4.14 and 4.13 lite works)

### ISSUE THREAD

**Issue by Dabanngg** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#24]
Rife 4.14 lite Ensamble_false not working (4.14 and 4.13 lite works) i tested in Enhancer app(from github) and other models works perfect but 4.14 lite seems to have problem. Thank You 
![image](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/assets/101319355/8daaaa99-2197-4a46-b0e9-c7de87fc07a7)

**Comment by TNTwise** [comment]
It needs convolutiondepthwise set to true when compiling, see if you can swap out the ncnn binary in enhancr but idk specifically how that works.

**Comment by Dabanngg** [comment]
Thanks For Your Fast response 

How can i do that?

**Comment by Dabanngg** [comment]
Can you compile it like pervious versions? (like 4.13 lite)

**Comment by TNTwise** [comment]
I dont use windows, but you should be able to find enhancr's install directory somewhere in %APPDATA%, in there, look for a binary (Im assuming it uses vapoursynth) called librife.dll create a backup of the original and replace with the one here. Unfortunately, I do not use windows or enhancr, but if that doesn't work you can always use a vapoursynth script to run rife.

**Comment by Dabanngg** [comment]
Thanks sir I replaced libride.dll and it Works Now!   Have a Good Day.

> I dont use windows, but you should be able to find enhancr's install directory somewhere in %APPDATA%, in there, look for a binary (Im assuming it uses vapoursynth) called librife.dll create a backup of the original and replace with the one here. Unfortunately, I do not use windows or enhancr, but if that doesn't work you can always use a vapoursynth script to run rife.
