### ISSUE TITLE
Convert model process

### ISSUE THREAD

**Issue by Siziff** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#26]
HI, can smb please explain how to convert the new Rife model from hzwer/Practical-RIFLE to ncnn format? 
I've tried to use: 
1. torch.jit.trace() and then convert .pt file through pnnx to ncnn
2. torch.onnx._export() and then onnx2ncnn from ncnn git

BUT NONE OF THEM WORKS. 
The models I received do not run in the Vulkan app on my phone. but I run models from this project that @styler00dollar converted.
Can someone explain how to convert models correctly?

**Comment by TNTwise** [comment]
https://github.com/TNTwise/REAL-Video-Enhancer/wiki/Convert-Rife-Models

**Comment by styler00dollar** [comment]
I wrote a guide [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/issues/37#issuecomment-1528440567). It is more complicated than just using `torch.onnx`.

**Comment by Siziff** [comment]
@styler00dollar  @TNTwise  I follow all the instructions, but I get an error. How did you fix this error? I get this error in both solutions.
```
TypeError: upsample_bilinear2d() received an invalid combination of arguments - got (Tensor, NoneType, bool, list), but expected one of:
 * (Tensor input, tuple of ints output_size, bool align_corners, tuple of floats scale_factors)
      didn't match because some of the arguments have invalid types: (Tensor, NoneType, bool, list)
 * (Tensor input, tuple of ints output_size, bool align_corners, float scales_h, float scales_w, *, Tensor out)
```

**Comment by TNTwise** [comment]
Did you replace x with im0,img1

**Comment by Siziff** [comment]
Yes, everything is as in the instructions @TNTwise

**Comment by TNTwise** [comment]
Are you using that specific torch version? It needs the one from the instructions to work with onnx export.

**Comment by TNTwise** [comment]
You can also use my script here on rife-v4.14 and compare to how you are exporting. You may need to download config.txt as well. https://github.com/TNTwise/ConvertRIFEtoNCNN-githubactions/blob/main/modify_train_log.py

**Comment by Siziff** [comment]
@TNTwise  thanks a lot for the script, I get the once file, but when I try to convert it to ncnn I get an error `Cast not supported yet!
# to=1`. If I use a sim, the model is converted to ncnn with no errors, BUT when I add these models to the [rife-ncnn-vulkan](https://github.com/nihui/rife-ncnn-vulkan) project and try to launch it, I get a black picture. What could be the problem?  
It's worth noting that when I run models from [here](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/blob/master/models/rife-v4.14_ensembleFalse/flownet.bin), everything works correctly..

**Comment by TNTwise** [comment]
You need to run it through onnxsim to remove cast.

**Comment by TNTwise** [comment]
You need to run it through onnxsim to remove cast. You can also try pnnx conversion to see if that works.
