### ISSUE TITLE
model=30

### ISSUE THREAD

**Issue by Asd-g** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#27]
[model=30](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/blob/master/RIFE/plugin.cpp#L379) probably should be `"/rife-v4.9_ensembleTrue"` (now it's  the same as `model=29`).

**Comment by styler00dollar** [comment]
Seems like a copy paste error. [Fixed](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/commit/362958cc8da3c3d3112dbec342702a17a23e188e)
