### ISSUE TITLE
Do the models: rife-v4.5 and rife-v4.6 have the fast=False parameter?

### ISSUE THREAD

**Issue by AIVFI** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#3]
First of all, many thanks for updating VapourSynth-RIFE-ncnn-Vulkan with the newest models.

I see that the models from rife-v4 to rife-v4.4 have two versions: the fastest and the slowest (the highest quality).
For the models from rife-v4.5 to rife-v4.6, the two versions differ in only one parameter: ensemble. 
I have a question: do both versions of these two latest models have the parameter: fast=False?

**Comment by styler00dollar** [comment]
If you look at the code, after 4.5 it was simply removed and it does not exist anymore. They both are *technically* fast=True since they don't use contextnet and unet.

**Comment by AIVFI** [comment]
Thanks
