### ISSUE TITLE
Failed to load model (49 and 50)

### ISSUE THREAD

**Issue by grosbecyk** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#37]
I am using release r9_v17 on mac x86. All models work fine except 49 and 50. It seems that a slash is missing in modelPath's declarations in plugin.cpp :

```
            case 48:
                modelPath += "/rife-v4.15_ensembleTrue";
                break;
            case 49:
                modelPath += "rife-v4.15_lite_ensembleFalse";
                break;
            case 50:
                modelPath += "rife-v4.15_lite_ensembleTrue";
                break;

            case 51:
                modelPath += "/rife-v4.16_lite_ensembleFalse";
```

btw, thanks a lot for the mac binary releases. Much appreciated!

**Comment by TNTwise** [comment]
Sorry I forgot the slash in the beginning of the string for those 2 models, you can override the model num with model_path for now

**Comment by styler00dollar** [comment]
Purged and recompiled v17, should be fixed.
