### ISSUE TITLE
invalid data found when processing input

### ISSUE THREAD

**Issue by idkgmv** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#39]
So I use Smoothie with this plugin , 
![image](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/assets/167709917/f2a76ca7-a0c0-43f9-85bd-72d55bbd9a0d)
 . When I contacted the smoothie staff they said 

The error is because of this plugin so go there and complain an issue 

So plz fix this

**Comment by styler00dollar** [comment]
It says:
```
LoadLibrary vulkan-1.dll failed 126
load vulkan driver failed
```
If vulkan doesn't work then this plugin won't as well. To me it looks like vulkan or the system is not set up properly and thus the plugin doesn't work. This isn't because of the plugin itself.
