### ISSUE TITLE
Bad(interlaced, overlayed like) inference output of `rife-4.5` and `rife-4.6` models

### ISSUE THREAD

**Issue by Justin62628** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#4]
Using the same script of inference implemented by nihui, the following models produce different outputs as followed:
(`uhd_mode = False` and `tta_mode = False`)
- `rife-v4_ensembleTrue_fastFalse` or `rife-v4_ensembleFalse_fastTrue`
![image](https://user-images.githubusercontent.com/37169106/195839324-95f09f41-cac3-4ebf-82dd-b52be133c249.png)
, which is quite normal, while: 

- `rife-4.5` and `rife-4.6`, no matter `ensemble` is True or False
![image](https://user-images.githubusercontent.com/37169106/195840075-f43d6d7a-d5bc-4dba-a9d3-71ff1523ae9b.png)
, definitely wrong.

There might be a problem with the quantitization or conversion of the `ensemble` feature. 
Would it be convenient for you to share the scripts for model conversions(pytorch model to ncnn `.params` & `.bins`)? Nihui says she converted the `rife-v4` model using `pnnx`, which could make a difference I guess.

**Comment by styler00dollar** [comment]
I don't use pnnx. I use self written code and workarounds to export. The model itself won't change anyway, only the param file. Please test with the vapoursynth code again.

**Comment by Justin62628** [comment]
uh you're right. 
lmao after some debug I found that using Intel GPU is the reason for that overlayed output.
NVIDIA GPU works like a charm.
