### ISSUE TITLE
"lite" models for 4.18/4.19/4.20 ?

### ISSUE THREAD

**Issue by luikaire** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#47]
WIll the "lite" versions be added for models 4.18/4.19 beta/4.20?

Also, the 4.15/4.16 lite versions seem to be faster (2x upsampling) than 4.17-lite. Is this expected behaviour?

**Comment by TNTwise** [comment]
No official lite versions for those models, they will be added if they are made. https://github.com/hzwer/Practical-RIFE here are where the models are listed, we just convert. Lite model performance can vary, that's expected.

**Comment by luikaire** [comment]
Ok. Closing here. Opened this issue in that repo. thanks
https://github.com/hzwer/Practical-RIFE/issues/87
