### ISSUE TITLE
Gimmick feature: model_s 

### ISSUE THREAD

**Issue by Selur** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#50]
Would be nice if you could add a parameter i.e. 'model_s' which could be used as alternative to 'model', so that one could set 'model_s' to the folder name of the model (in the models-folder) instead of having to use an integer.
This would allow to:
a. easier see, in the rife.RIFE-call, which model is used (independent of the release)
b. more intuitive usage of rife.RIFE

Thanks for thinking this over!

**Comment by TNTwise** [comment]
model_path parameter should do this already.

**Comment by Selur** [comment]
DOH,... I totally overlooked that. Thanks!
