### ISSUE TITLE
4:3 video distortion is not fixed for 4.25

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#54]
I still get this @TNTwise 
![image](https://github.com/user-attachments/assets/a76665a1-0c60-4171-a410-2b56f573680f)

**Comment by TNTwise** [comment]
I tested 800x600, did you download the new model bin and param?

**Comment by natural-harmonia-gropius** [comment]
> I tested 800x600

Same artifacts in 800x600.
![image](https://github.com/user-attachments/assets/8672e8f8-02a9-495f-b7f9-4e71892372c9)

> did you download the new model bin and param?

Yes.
![image](https://github.com/user-attachments/assets/f3be9dfa-aa9d-43b4-b711-7cd7202799d5)

**Comment by TNTwise** [comment]
Could be an ncnn issue, I reconverted with every trick I know to fix it, and it works with rife-ncnn-vulkan non vs.

**Comment by TNTwise** [comment]
Try interpolating 2 800x600 images with this, and see if you get the same issue. https://github.com/TNTwise/rife-ncnn-vulkan

**Comment by natural-harmonia-gropius** [comment]
> if you get the same issue.

Hmm... no problem with non vs.

**Comment by TNTwise** [comment]
Only difference is ncnn version, I'll see if downgrading the ncnn version here fixes the issue

**Comment by TNTwise** [comment]
created a pr that should fix this

**Comment by styler00dollar** [comment]
Should be fixed now. Made a new release.
