### ISSUE TITLE
4.25 lite from practical_rife

### ISSUE THREAD

**Issue by luikaire** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#57]
4.25.lite has been released at https://drive.google.com/file/d/1zlKblGuKNatulJNFf5jdB-emp9AqGK05/view?usp=share_link from https://github.com/hzwer/Practical-RIFE/

It would be nice if this could be ported here. thanks.

**Comment by styler00dollar** [comment]
Added with [r9_mod_v28](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/releases/tag/r9_mod_v28).
