### ISSUE TITLE
new version of rife-cnn-vulkan-20221029

### ISSUE THREAD

**Issue by skiqing** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#6]
new version of rife-cnn-vulkan-20221029

https://github.com/nihui/rife-ncnn-vulkan/releases/tag/20221029

this new version of rife-v4 and rife-v4.6 now support tta
-x enable space tta mode
-z enable temporal tta mode
will you add support for VapourSynth-RIFE-ncnn-Vulkan?

because i use your version of VapourSynth-RIFE-ncnn-Vulkan

**Comment by styler00dollar** [comment]
There isn't something new to add. Temporal tta means ensemble and you can already do that. Spacial tta means to average flipped output frames and you can do that in VapourSynth yourself.
