### ISSUE TITLE
Artifacts with models 25+, model or support issue?

### ISSUE THREAD

**Issue by Selur** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#60]
Models:
69 = rife-v4.25 (ensemble=False)
70 = rife-v4.25-lite (ensemble=False)
71 = rife-v4.25-heavy (ensemble=False)
72 = rife-v4.26 (ensemble=False)
all cause artifacts:
![grafik](https://github.com/user-attachments/assets/49e69928-e524-4f03-83af-6942df73881a)
which the previous models did not create
![grafik](https://github.com/user-attachments/assets/2c37532a-302c-4175-b6bb-63548843f0cd)
So I was wondering it this the models themselves or is something broken with their support?

**Comment by Selur** [comment]
Yes, it also happens with v27.
(side note: 4.25+ work fine in vs-rife and vs-mlrt, so it's not a general problem of the model)
My source: https://drive.google.com/file/d/1xchtRU6uZyLm9xJWh4HgNxDrSqC70zhl/view?usp=drive_link
It does **not** happen if I resize the source beforehand to 1280x704 (good catch), so it seems to be resolution dependent. :)
(works with both v27 and v30 if I resize beforhand)

**Comment by TNTwise** [comment]
What resolution does it artifact at?

**Comment by Selur** [comment]
640x352: fails (= artifacts)
1280x704: works (= no artifacts)
720x396:  fails
960x528: fails
1024x564:  works

**Comment by TNTwise** [comment]
I have done quite a bit of testing, but have not been able to fix it with this repo, but manually padding to 64 in vapoursynth seems to mitigate the issue.

```
import os
import vapoursynth as vs

core = vs.core
core.num_threads = 4  # can influence ram usage
core.std.LoadPlugin(path="librife.so")
clip = core.bs.VideoSource(source="./test.mp4")
clip = vs.core.resize.Bicubic(clip, format=vs.RGBS, matrix_in_s="709")
# Calculate padding to make width and height multiples of 64
pad_width = (64 - (clip.width % 64)) % 64
pad_height = (64 - (clip.height % 64)) % 64

clip = core.std.AddBorders(clip, right=pad_width, bottom=pad_height)

clip = core.rife.RIFE(
    clip,
    model_path='models/rife-v4.26-large_ensembleFalse',
    factor_num=2,
    gpu_id=0,
    gpu_thread=2,
    tta=False,
    uhd=False,
    skip=False,
    sc=False,
)

# Crop the added borders
clip = core.std.Crop(clip, right=pad_width, bottom=pad_height)

clip = vs.core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s="709")
clip.set_output()
```

**Comment by styler00dollar** [comment]
Should be fixed with [r9_mod_v32](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/releases/tag/r9_mod_v32).

**Comment by Selur** [comment]
Thanks
