### ISSUE TITLE
Scene Change Stutter

### ISSUE THREAD

**Issue by jhardingful** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#62]
When RIFE detects a scene cut it repeats the frame to prevent a garbled frame between the scene change. However, on a panning shot, it comes across as a stutter as the final frame is duplicated (or very similar). 

Is there a way for the system to anticipate the final frame and interpolate into it, the same as it does with all the other frames? So that a panning shot ends with the same rate of movement rather than slowing down abruptly on the last frame?

I'm not sure how this would be achieved, but I guess on the final frame instead of duplicating a frame, it would use the motion vectors to guess what the next frame would be? Or somehow the system would anticipate what the final frame of the scene is and interpolate towards it?

**Comment by styler00dollar** [comment]
Scene change detection (or rather shot boundary detection) is not really the focus of this plugin. [I trained and use some models to do this task which you could attempt to use on cpu or port to ncnn](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/main/src/scene_detect.py). Alternatively you can use [wwxd](https://github.com/dubhater/vapoursynth-wwxd) or [scxvid](https://github.com/dubhater/vapoursynth-scxvid), but these 2 probably won't be better than [SCDetect](https://github.com/vapoursynth/vs-miscfilters-obsolete). All this plugin does is copy frames which have the frame property `_SceneChangeNext` set and does not do detection. 

https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/blob/63d5a7b1cf2aa387feeddb3466f1eccd32bc3553/RIFE/plugin.cpp#L101

[SCDetect](https://github.com/vapoursynth/vs-miscfilters-obsolete) is usually recommended if models are not used, but you can set the property however you want. [You can also replace frames outside of this plugin](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/2543035440c9cddfdff749dab2d4180b0e0d5963/custom_scripts/inference_rife_dedup_scene_change.py#L58) within the same vapoursynth file. [This topic is a separate research field](https://paperswithcode.com/task/camera-shot-boundary-detection).
