### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#8]
Thanks for sharing this great work.
 I'm used to running github projects like this that use python scrips, but I'm lost with how to set this one up. Would you know of any detailed instructions or tutorials for this?

**Comment by styler00dollar** [comment]
Compile it with the given instructions in the readme or download the release. Afterwards you can use it with this for example:
```
clip = core.rife.RIFE(clip, model=9, factor_num=2, gpu_id=0, gpu_thread=4, tta=False, uhd=False, skip=False, sc=False)
```
Certain features will require more dependencies, like `skip` needs `vmaf` and `sc` needs `vs-miscfilters-obsolete`. In my docker I compile it for linux [here](https://github.com/styler00dollar/VSGAN-tensorrt-docker/blob/aaaa700e83c9b4037ab818581e12fbb1be4e714d/Dockerfile#LL432C1-L432C1). If you don't know how to use vapoursynth, you should look that up.

**Comment by styler00dollar** [comment]
I guess I can close due to inactivity.

**Comment by noobtoob4lyfe** [comment]
Sorry for the delay.  Thank you for your help!

**Comment by styler00dollar** [comment]
No, you need to get familiar with vapoursynth scripts.
