### ISSUE TITLE
RIFE 4.7 support?

### ISSUE THREAD

**Issue by Selur** [styler00dollar/VapourSynth-RIFE-ncnn-Vulkan#9]
Any plans to support RIFE 4.7?

**Comment by styler00dollar** [comment]
Was busy, but I did add the PyTorch code into [my vsgan repo](https://github.com/styler00dollar/VSGAN-tensorrt-docker/commit/1dc85200a86e13ebb50f13840ad78a90273909c3). If the onnx works fine, only thing left is to convert to bin/param. Should come soon.

**Comment by styler00dollar** [comment]
Took longer since the rife 4.7 architecture differs more than usual and required different editing of the param file. Release [here](https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/releases/tag/r9_mod_v5).

**Comment by Selur** [comment]
Thanks for the update, did a quick test and it seems to work fine. 👍

**Comment by hooke007** [comment]
rife4.8 has come...

**Comment by mafiosnik777** [comment]
> rife4.8 has come...

https://github.com/styler00dollar/VapourSynth-RIFE-ncnn-Vulkan/pull/11

**Comment by Selur** [comment]
Nice!

**Comment by styler00dollar** [comment]
Luckily the 4.8 architecture seems to be identical to 4.7, so exporting to onnx could be done with the same script and param file was just copied. Next time please a new issue for new rife versions though.
